### PR TITLE
Turned creation of inmate URLs into a generator and minor code cleanup

### PR DESCRIPTION
**Pull request by nwinklareth**
Hi David & Wilberto,
It was fun to work again on this project.

I was not able to run what I did so please review it carefully, and even try it out before adopting it.

Norbert

### CODE REVIEW

**Comment by eads** [comment]
Hey Norbert! I figured you were busy with life stuff, great to have you back in the mix!! 

This all looks wonderful. I wanted to add tests for a couple of these pieces as it is, so I think I'll go ahead and do that before accepting (and of course making sure it all works). Let me know how we can make it easier for you to run.

I always forget I can generate a dict via comprehension, glad you caught that.

**Comment by nwinklareth** [comment]
I am retracting this change request until I can provide tests for it.

**Comment by eads** [comment]
Okay -- I got a little sidetracked by a few other projects (and one fairly bad bug in this one). Let's figure out how to make it easier for you to run locally first; that seems like a significant blocker.

**Comment by nwinklareth** [comment]
No problems I got caught in my eddies including having my new dell laptop
brick on me.

I am working on getting my environment becable to ececute the project and
to that I need to that build it up which means going back to square one. I
have started that by retracting, closing, the pull request and I will be
adding in the changes piece by piece and creating a working environment
that includes testing via py.test - wow what a piece of magic that is.

So you will see a bunch of pull request starting from the mundane and
trival to hopefully more meaningful ones.

Norbert


On Aug 23, 2017 2:44 PM, "David Eads" <notifications@github.com> wrote:

Okay -- I got a little sidetracked by a few other projects (and one fairly
bad bug in this one). Let's figure out how to make it easier for you to run
locally first; that seems like a significant blocker.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/propublica/cookcountyjail2/pull/65#issuecomment-324426469>,
or mute the thread

**Pull request closed without merging**
